### ISSUE TITLE
different variable name

### ISSUE THREAD

**Issue by dkatsios** [cocodataset/panopticapi#1]
in line:
`print('no prediction for the image with id: {}'.format(img_id))`
I think the variable `img_id` should be `image_id`

**Comment by alexander-kirillov** [comment]
Yes, you're right. Thank you for spotting the bug! It is fixed now.

**Comment by dkatsios** [comment]
also in line:
`if intersection / pred_info['area'] > 0.5`
there is the case that the `area` key has not been added to the `pred_info` dict at the previous stage and thus raise an `key` error.
(Unfortunately I ended up with a couple of empty predictions and had to find it out!)

**Comment by alexander-kirillov** [comment]
I added some additional sanity checks for prediction data. It should help with such problems.
