### ISSUE TITLE
Using cityscapes dataset

### ISSUE THREAD

**Issue by YuShen1116** [cocodataset/panopticapi#13]
Hi, I'm trying to run evaluation on cityscapes dataset. However, I can't find proper coco format of the gt files. I found a convertor in repo https://github.com/facebookresearch/Detectron/blob/master/tools/convert_cityscapes_to_coco.py.
But it can't work for panoptic evaluation. Could anyone please tell me there can I find a gt files for cityscapes dataset?

Thank you

**Comment by alexander-kirillov** [comment]
Hi Yu,

Please find a script to convert Cityscapes GT format to panoptic format used by this repository here: https://github.com/cocodataset/panopticapi/blob/master/cityscapes_gt_converter/cityscapes_panoptic_converter.py

Let me know if you have any problems with it.

**Comment by YuShen1116** [comment]
@alexander-kirillov  Thanks a lot! That's very helpful
