### ISSUE TITLE
Convert the annotations of thing to COCO instance format

### ISSUE THREAD

**Issue by karenyun** [cocodataset/panopticapi#3]
Hi, thanks for the work!
I have some questions about the "instance_data.py":
the line:
`pan = pan_format[:,:,0] + 256 * pan_format[:,:,1] + 256*256*pan_format[:,:,2]`
Could you give some details about this line?
When I print the results after converting to the COCO instance format, it seems that there are all the binary encoding for the "segmentation" rather than the decimal code as the COCO instance format.
Thanks very much!

**Comment by alexander-kirillov** [comment]
Hi Yun,

`pan = pan_format[:,:,0] + 256 * pan_format[:,:,1] + 256*256*pan_format[:,:,2]`
This line converts RGB values to IDs that encode different segments in panoptic COCO format. Please see, note 2 in panoptic segmentation section of [COCO data format](http://cocodataset.org/#format-data).

> When I print the results after converting to the COCO instance format, it seems that there are all the binary encoding for the "segmentation" rather than the decimal code as the COCO instance format.

Original COCO segmentations are stored as polygons (decimal code represents their vertices) instance_data.py stores in the "segmentation" field RLE encoding of the corresponding mask.  Note that [COCO API](https://github.com/cocodataset/cocoapi) supports the format as well as the polygon description. Current version of [Detectron](https://github.com/facebookresearch/Detectron), however, does not support RLE encoded segments. There is a [pull request](https://github.com/facebookresearch/Detectron/pull/458) you can use to add the support.

I hope this answers your question. Let me know if something else is not clear.

**Comment by karenyun** [comment]
Hi, thanks for your quick reply, I will read them carefully!

**Comment by karenyun** [comment]
Hi, I think I have known how to make it, thanks!

**Comment by alexander-kirillov** [comment]
Hi Shen,

In general, IDs are arbitrary. So you can assign any color to each segment except [0, 0, 0]. The only requirement - for different segments in the same image colors must be different.

If you want IDs that look nice, then there is a class `ColorGenerator` in _format_converter.py_ script. This class allows to generate colors for segments so that they are similar to class color but each segment will have a unique color. I hope this helps in your case.

**Comment by karenyun** [comment]
got it, thanks!

**Comment by ranjiewwen** [comment]
> Hi Shen,
> 
> In general, IDs are arbitrary. So you can assign any color to each segment except [0, 0, 0]. The only requirement - for different segments in the same image colors must be different.
> 
> If you want IDs that look nice, then there is a class `ColorGenerator` in _format_converter.py_ script. This class allows to generate colors for segments so that they are similar to class color but each segment will have a unique color. I hope this helps in your case.

i also have some question: 
https://github.com/cocodataset/panopticapi/issues/15
