### ISSUE TITLE
Missing segmentations folder?

### ISSUE THREAD

**Issue by rlan** [cocodataset/panopticapi#4]
I'm trying to run visualization.py as is. This folder 

https://github.com/cocodataset/panopticapi/blob/d9c2c1fbaa69cb78c86f1a3a8d6cb11aa8698120/visualization.py#L15

doesn't exist in the repo.

**Comment by rlan** [comment]
![image](https://user-images.githubusercontent.com/1386868/43129602-c8cf6b04-8f6f-11e8-8647-7c3e7a83e25c.png)

Works now. Thanks for the speedy fix!

**Comment by hszhao** [comment]
It seems the script 'visualization.py' just reads a color image and shows the boundary? Also types in line 234 of file 'evaluation.py': 'gorund turth' should be 'ground truth'.
