### ISSUE TITLE
convert custom dataset to panoptic coco format

### ISSUE THREAD

**Issue by mqbin** [cocodataset/panopticapi#57]
Hi, @alexander-kirillov , I have a custom dataset with annotations including instance segmentation masks and semantic segmentation masks. I generate this dataset in 2channels format, but I found that 2channels2panoptic_coco_format.py doesn't give 'bbox' and 'area' in 'segments_info', which makes the panoptic segmentation model unable to train.  So, I convert it to instance segmentation format, and then try to convert it to panoptic segmentation format.But I got the following error, 

line 68, in convert_detection_to_panoptic_coco_format_single_core
raise Exception("Segments for image {} overlap each other.".format(img_id))

Exception: Segments for image 1 overlap each other.

This problem has been bothering me for a long time. And How can I get the correct data format for panoptic segmentation?

**Comment by Sue-Tang-Up** [comment]
I have met the same problem, would you like to tell me the solution?
